name: 'Setup Platypus'
description: 'Download and install the Platypus command line tool.'
author: 'Sveinbjorn Thordarson'
branding:
  icon: 'box'
  color: 'yellow'
inputs:
  version:
    description: 'The version of Platypus to install.'
    required: false
    default: '5.5.0'
runs:
  using: "composite"
  steps:
    - name: Install Platypus
      shell: bash
      run: |
        PLATYPUS_VERSION="${{ inputs.version }}"
        # Check if already installed
        if command -v platypus &> /dev/null; then
          echo "Platypus is already installed."
          exit 0
        fi
        
        DOWNLOAD_URL="https://github.com/sveinbjornt/Platypus/releases/download/v${PLATYPUS_VERSION}/platypus${PLATYPUS_VERSION}.zip"
        ZIP_FILE="platypus${PLATYPUS_VERSION}.zip"
        
        echo "Downloading Platypus v${PLATYPUS_VERSION} from ${DOWNLOAD_URL}..."
        curl -L -O "$DOWNLOAD_URL"
        
        echo "Unzipping..."
        unzip -q "$ZIP_FILE"
        
        echo "Installing Platypus..."
        # The installation script relies on being in the Resources folder
        cd Platypus.app/Contents/Resources
        
        # Pass "." as the directory argument to be safe, as script uses `cd "$1"`
        sudo bash InstallCommandLineTool.sh "."
        
        echo "Platypus installed successfully."
        platypus -v